grep -in 'scrudex2' webapp.js
grep -in 'it_recordies' webapp.js
grep -in 'tbl_index' webapp.js
grep -in 'rank' webapp.js
grep -in 'materiomics_name' webapp.js
grep -in 'industries' webapp.js
grep -in 'revenue' webapp.js
grep -in 'project_year' webapp.js
grep -in 'employees' webapp.js
grep -in 'market_cap' webapp.js
grep -in 'headquarters' webapp.js
